server:
  port: 20080

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    url: jdbc:postgresql://10.10.129.199:5432/ledger
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      max-lifetime: 600000

mybatis:
  type-aliases-package: com.airwallex.batchjobs.repository.repository
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

application:
  job:
  batch:
    envTag: dev

dispatcher:
  starter:
    name: CoreDispatcher
    runFlag: true
  dispatcher-one:
    name: TEST_ONE
    coreSize: 10
    maxSize: 10
    queueSize: 100
    noTaskSleepSeconds: 5

  dispatcher-two:
    name: TEST_TWO
    coreSize: 5
    maxSize: 5
    queueSize: 1000
    hungrySize: 800
    noTaskSleepSeconds: 60

management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true